install-bash-rc:
	ln -sf ${CURDIR}/.bash_profile ${HOME}/.bash_profile
	ln -sf ${CURDIR}/.bashrc ${HOME}/.bashrc
	ln -sf ${CURDIR}/.profile ${HOME}/.profile
	ln -sf ${CURDIR}/.xinitrc ${HOME}/.xinitrc
