install-bash-rc:
	ln -s ${CURDIR}/.bash_profile ${HOME}/.bash_profile
	ln -s ${CURDIR}/.bash_profile ${HOME}/.bashrc
	ln -s ${CURDIR}/.profile ${HOME}/.profile
	ln -s ${CURDIR}/.xinitrc ${HOME}/.xinitrc
