install-pip:
	wget -O /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
	sudo python /tmp/get-pip.py

install-pip3:
	wget -O /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
	sudo python3 /tmp/get-pip.py
